AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5

  Exclude:
  - "2019/**/*"
  - "2020/**/*"
  - "spec/spec_helper.rb"

require:
- rubocop-rspec
- rubocop-rake

Lint/AmbiguousOperatorPrecedence:
  Enabled: No

Metrics/BlockLength:
  Exclude:
  - "spec/**/*"

RSpec/SpecFilePathFormat:
  Enabled: No

RSpec/IndexedLet:
  Enabled: No

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/MixinUsage:
  Enabled: No

Style/Documentation:
  Enabled: No

Style/CharacterLiteral:
  Enabled: No

Security/Eval:
  Enabled: No

Style/ParallelAssignment:
  Enabled: No
