# frozen_string_literal: true

require_relative "../../../2022/23/lib"

RSpec.describe Year2022::Day23 do
  include described_class

  let(:input) do
    %(..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............
)
  end

  describe "problem1" do
    it "returns 110 for test input" do
      expect(problem1(process_input(input))).to eq(110)
    end
  end

  describe "problem2" do
    it "returns 20 for test input" do
      expect(problem2(process_input(input))).to eq(20)
    end
  end
end
