# frozen_string_literal: true

require_relative "../../../2022/22/lib"

RSpec.describe Year2022::Day22 do
  include described_class

  let(:input) do
    %(        ...#
        .#..
        #...
        ....
...#.......#
........#...
..#....#....
..........#.
        ...#....
        .....#..
        .#......
        ......#.

10R5L5R10L4R5L5
)
  end
  let(:input_empty) do
    %(     ..........
     ..........
     ..........
     ..........
     ..........
     .....
     .....
     .....
     .....
     .....
..........
..........
..........
..........
..........
.....
.....
.....
.....
.....

1R6L20R20
)
  end

  describe "process_input" do
    it "consumes multiline string and returns processed input" do
      expect(process_input(input)).to match([an_instance_of(Hash), "10R5L5R10L4R5L5"])
    end
  end

  describe "problem1" do
    it "returns 6032 for test input" do
      expect(problem1(process_input(input))).to eq(6032)
    end
  end

  describe "problem2" do
    it "returns 5031 for test input" do
      expect(problem2(process_input(input), test_net: true)).to eq(5031)
    end

    it "returns n for empty input" do
      expect(problem2(process_input(input_empty))).to eq(7 * 1000 + 7 * 4 + 1)
    end
  end
end
