# frozen_string_literal: true

require_relative "../../../2025/07/lib"

RSpec.describe Year2025::Day07 do
  include described_class

  let(:input) do
    %(.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
)
  end
  let(:processed_input) do
    %w[
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    ]
  end

  describe "process_input" do
    it "consumes multiline string and returns processed input" do
      expect(process_input(input)).to eq(processed_input)
    end
  end

  describe "problem1" do
    it "returns 21 for test input" do
      expect(problem1(processed_input)).to eq(21)
    end
  end

  describe "problem2" do
    it "returns 40 for test input" do
      expect(problem2(processed_input)).to eq(40)
    end
  end
end
